### PR TITLE
feat(ejbca): deployment changes for ejbca integration

### PR DESCRIPTION
**Pull request by jiparis**
This is a follow up of https://github.com/chainloop-dev/chainloop/pull/1026 with the required changes to properly configure the Chainloop chart with EJBCA.

Diff without any additional configuration:
```
--- before.yaml	2024-06-26 21:13:16
+++ after.yaml	2024-06-26 21:13:06
@@ -220,7 +220,7 @@
   name: test-chainloop-cas
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -234,7 +234,7 @@
   name: test-chainloop-controlplane
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -280,7 +280,7 @@
   name: test-chainloop-cas
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -307,7 +307,7 @@
   name: test-chainloop-cas-jwt-public-key
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -324,7 +324,7 @@
   name: test-chainloop-controlplane
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -333,9 +333,9 @@
 type: Opaque
 data:
   # We store it also as a different key so it can be reused during upgrades by the common.secrets.passwords.manage helper
-  generated_jws_hmac_secret: "Ylk5b0g4YlBBMw=="
+  generated_jws_hmac_secret: "S2d5dk52Z1ZaaQ=="
   db_migrate_source: "cG9zdGdyZXM6Ly9jaGFpbmxvb3A6Y2hhaW5sb29wcHdkQHRlc3QtcG9zdGdyZXNxbDo1NDMyL2NoYWlubG9vcC1jcD9zc2xtb2RlPWRpc2FibGU="
-stringData:
+stringData:  
   config.secret.yaml: |
     data:
       database:
@@ -358,7 +358,7 @@
       # HMAC key used to sign the JWTs generated by the controlplane
       # The helper returns the base64 quoted value of the secret
       # We need to remove the quotes and then decoding it so it's compatible with the stringData stanza
-      generated_jws_hmac_secret: "bY9oH8bPA3"
+      generated_jws_hmac_secret: "KgyvNvgVZi"
 
       # Private key used to sign the JWTs meant to be consumed by the CAS
       cas_robot_account_private_key_path: "/secrets/cas.private.key"
@@ -370,7 +370,7 @@
   name: test-chainloop-controlplane-jwt-cas
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -408,7 +408,7 @@
   name: test-chainloop-cas
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -436,7 +436,7 @@
   name: test-chainloop-controlplane
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -1023,7 +1023,7 @@
   name: test-chainloop-cas-api
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -1051,7 +1051,7 @@
   name: test-chainloop-cas
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -1077,7 +1077,7 @@
   name: test-chainloop-controlplane-api
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -1105,7 +1105,7 @@
   name: test-chainloop-controlplane
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -1332,7 +1332,7 @@
   name: test-chainloop-cas
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -1348,9 +1348,9 @@
   template:
     metadata:
       annotations:
-        checksum/config: 2e369304caacfc3e57a4739c87d1c482f806bf2f905000f441ef47e58d8326a3
-        checksum/config-secret: cf09878bc234aa3a905491e58f4d69aa78cfbe11715c1963aa6bb8985a50c960
-        checksum/public-key-secret: c0444e34af2e02df26dc5950167a27ba96e63248396509094e8534fdd6fc5891
+        checksum/config: af1de31972b6e9dd2dda1f5e744794b89d6f8d067f73ab6d37c1dc1589c988bb
+        checksum/config-secret: e4524e938577d85d11e67225d35d390fed9991027b382cec6d527ad9f255ee7e
+        checksum/public-key-secret: 77ac8d4465985c1487c609df051e0296090f1bc2f0ac6bff65bf07378cc93393
       labels:
         app.kubernetes.io/name: chainloop
         app.kubernetes.io/instance: test
@@ -1414,7 +1414,7 @@
   name: test-chainloop-controlplane
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -1430,9 +1430,9 @@
   template:
     metadata:
       annotations:
-        checksum/config: b39ab1fd7ee1fbe3a2c60b8e9cad53f9c30961be5cd57f80f0767abbae65db46
-        checksum/secret-config: 964b0c214dd9396b3531c10dbcb7bbef897b606a03ea50713c76c91c152dd8b1
-        checksum/cas-private-key: 2f80993041c90d8a8f81b3b151f214be34009bcdb17a715426b24a707a0725c6
+        checksum/config: 75e9d2268a4c984adc62e982260205b85d4d2006b794d2b25581cb3c624a42cf
+        checksum/secret-config: d5b602f5b8c0cf03d72bed1671eb43bc7111113bbe649681f39cf990c7950465
+        checksum/cas-private-key: 02bfcc2663a4a0b35e63dd60d916ab115938d65d42fe88dc4d110e60ea703e1f
         kubectl.kubernetes.io/default-container: controlplane
       labels:
         app.kubernetes.io/name: chainloop
```

This is how it looks like with EJBCA configuration options:
```
--- before.yaml	2024-06-26 21:13:16
+++ after.yaml	2024-06-26 21:27:37
@@ -220,7 +220,7 @@
   name: test-chainloop-cas
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -234,7 +234,7 @@
   name: test-chainloop-controlplane
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -280,7 +280,7 @@
   name: test-chainloop-cas
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -307,7 +307,7 @@
   name: test-chainloop-cas-jwt-public-key
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -324,7 +324,7 @@
   name: test-chainloop-controlplane
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -333,9 +333,18 @@
 type: Opaque
 data:
   # We store it also as a different key so it can be reused during upgrades by the common.secrets.passwords.manage helper
-  generated_jws_hmac_secret: "Ylk5b0g4YlBBMw=="
+  generated_jws_hmac_secret: "WUl2Q3FqTU5GbA=="
   db_migrate_source: "cG9zdGdyZXM6Ly9jaGFpbmxvb3A6Y2hhaW5sb29wcHdkQHRlc3QtcG9zdGdyZXNxbDo1NDMyL2NoYWlubG9vcC1jcD9zc2xtb2RlPWRpc2FibGU="
 stringData:
+  ejbca.secret.yaml: |
+    certificate_authority:
+      ejbca_ca:
+        cert_path: "/ca_secrets/ejbca_client.cert"
+        key_path:  "/ca_secrets/ejbca_client.key"
+        server_url: "https://host/ejbca"
+        certificate_profile_name: "Profile"
+        end_entity_profile_name: "Entity"
+        certificate_authority_name: "CANAME"  
   config.secret.yaml: |
     data:
       database:
@@ -358,10 +367,28 @@
       # HMAC key used to sign the JWTs generated by the controlplane
       # The helper returns the base64 quoted value of the secret
       # We need to remove the quotes and then decoding it so it's compatible with the stringData stanza
-      generated_jws_hmac_secret: "bY9oH8bPA3"
+      generated_jws_hmac_secret: "YIvCqjMNFl"
 
       # Private key used to sign the JWTs meant to be consumed by the CAS
       cas_robot_account_private_key_path: "/secrets/cas.private.key"
+---
+# Source: chainloop/templates/controlplane/ejbca_ca.secret.yaml
+apiVersion: v1
+kind: Secret
+metadata:
+  name: test-chainloop-controlplane-keyless-ejbca-ca
+  labels:
+    app.kubernetes.io/name: chainloop
+    helm.sh/chart: chainloop-1.70.1
+    app.kubernetes.io/instance: test
+    app.kubernetes.io/managed-by: Helm
+    app.kubernetes.io/version: "v0.92.7"
+    app.kubernetes.io/part-of: chainloop
+    app.kubernetes.io/component: controlplane
+type: Opaque
+data:
+  ejbca_client.cert: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNekNDQVp1Z0F3SUJBZ0lVYjBMaTdHMnpKVUdYYldZN2MvemMwc3hueDg0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1lURWpNQ0VHQ2dtU0pvbVQ4aXhrQVFFTUUyTXRNR3Q0WkRCMGRUQXpkbTg1WW1SMk9EWXhGVEFUQmdOVgpCQU1NREUxaGJtRm5aVzFsYm5SRFFURWpNQ0VHQTFVRUNnd2FSVXBDUTBFZ1EyOXVkR0ZwYm1WeUlGRjFhV05yCmMzUmhjblF3SGhjTk1qUXdOakkxTVRBME9UQTBXaGNOTWpVd05qSTFNVEEwT1RBeldqQXZNUzB3S3dZRFZRUUQKRENSbVkyVXdOV1EwT1MxaU5qTXpMVFE0TmpJdFltVXhaQzB6TXpRMU1EZ3haV05oWldFd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBVGxselZ4VTNYNFpteUNSTS9pQ05PYUs2eGNLdEI0MHcxRXIvc3hFL2toCnQ2Q1FqSldPUWE5bG9TN3FtdFdzWWJiaXNiU0V2KzBQc3VTcXlyMlZmcURBbzJBd1hqQU1CZ05WSFJNQkFmOEUKQWpBQU1COEdBMVVkSXdRWU1CYUFGSStYUWUrV2lVNGRkYVhvRXhBTnhtVndFUllJTUIwR0ExVWREZ1FXQkJTRwoweUV6YTZZSEErbDBScmNReWlINklWSk1XREFPQmdOVkhROEJBZjhFQkFNQ0I0QXdEUVlKS29aSWh2Y05BUUVMCkJRQURnZ0dCQUhPbGVKUlVEUzZtV1dwb0V5L0RLM3ZDcEw5a0RVamxnZGU4aklXU0NyclJCZnlhdzR5eExNd3QKb0pra0FsWW1VRlJhOVYxa1kwN0wxelBUWFc2WC82YlNuRGRZL1ZuTDVNQWJPZm9vRWU3NVdnQkxVdWFnN0RTQwpVNHFsSTNObGEzVFZDS1I1Mm5pY0NGVWFCc1lHWFZYajVLODUrV3FVYnlrbys0dENITWpIZGNRM3JZanpLSnFnCjBQQkZnakxSeU04b0treFNKVjFwY1FlbmtCd0Y0RUpWcVNIcHBxYmpaQ0tiQmZvekdoRmp2UExlcUphZ28vVGcKdVpKaVhYdHV3eFhQNCttTkZaT3VSYVcrUW0xNjRJRUkrbDRTbnE4b0hwcTlsU0N3Ulo0UzFaTTBQVG1qem9aeApZSUI3QjhzWllVMTFxWVgvTjhWcExOZnBSWXJHM1cwWnI3Y0trYTFablRkQng0WE5ZME1uRDUwUG1rbGNZSmlXClVkcVN2ZVM3Ymx3UDIwdGhCUGQ5M1Zkc2o3dlJMaGZzOVlhTjNOSVlyb0wvbk90elpabWRucUgwbzRQWmZBL0QKN3lHbjhsM0VGU2IzeWlRVW5jeUk4UUhjcEt3MDF6NzdPWWpFVnVuV1F5WUE1bE5oNlZ6VVFxMy9GNmpmblZ1cAp1NWpNOUMrc0RnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
+  ejbca_client.key: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNekNDQVp1Z0F3SUJBZ0lVYjBMaTdHMnpKVUdYYldZN2MvemMwc3hueDg0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1lURWpNQ0VHQ2dtU0pvbVQ4aXhrQVFFTUUyTXRNR3Q0WkRCMGRUQXpkbTg1WW1SMk9EWXhGVEFUQmdOVgpCQU1NREUxaGJtRm5aVzFsYm5SRFFURWpNQ0VHQTFVRUNnd2FSVXBDUTBFZ1EyOXVkR0ZwYm1WeUlGRjFhV05yCmMzUmhjblF3SGhjTk1qUXdOakkxTVRBME9UQTBXaGNOTWpVd05qSTFNVEEwT1RBeldqQXZNUzB3S3dZRFZRUUQKRENSbVkyVXdOV1EwT1MxaU5qTXpMVFE0TmpJdFltVXhaQzB6TXpRMU1EZ3haV05oWldFd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBVGxselZ4VTNYNFpteUNSTS9pQ05PYUs2eGNLdEI0MHcxRXIvc3hFL2toCnQ2Q1FqSldPUWE5bG9TN3FtdFdzWWJiaXNiU0V2KzBQc3VTcXlyMlZmcURBbzJBd1hqQU1CZ05WSFJNQkFmOEUKQWpBQU1COEdBMVVkSXdRWU1CYUFGSStYUWUrV2lVNGRkYVhvRXhBTnhtVndFUllJTUIwR0ExVWREZ1FXQkJTRwoweUV6YTZZSEErbDBScmNReWlINklWSk1XREFPQmdOVkhROEJBZjhFQkFNQ0I0QXdEUVlKS29aSWh2Y05BUUVMCkJRQURnZ0dCQUhPbGVKUlVEUzZtV1dwb0V5L0RLM3ZDcEw5a0RVamxnZGU4aklXU0NyclJCZnlhdzR5eExNd3QKb0pra0FsWW1VRlJhOVYxa1kwN0wxelBUWFc2WC82YlNuRGRZL1ZuTDVNQWJPZm9vRWU3NVdnQkxVdWFnN0RTQwpVNHFsSTNObGEzVFZDS1I1Mm5pY0NGVWFCc1lHWFZYajVLODUrV3FVYnlrbys0dENITWpIZGNRM3JZanpLSnFnCjBQQkZnakxSeU04b0treFNKVjFwY1FlbmtCd0Y0RUpWcVNIcHBxYmpaQ0tiQmZvekdoRmp2UExlcUphZ28vVGcKdVpKaVhYdHV3eFhQNCttTkZaT3VSYVcrUW0xNjRJRUkrbDRTbnE4b0hwcTlsU0N3Ulo0UzFaTTBQVG1qem9aeApZSUI3QjhzWllVMTFxWVgvTjhWcExOZnBSWXJHM1cwWnI3Y0trYTFablRkQng0WE5ZME1uRDUwUG1rbGNZSmlXClVkcVN2ZVM3Ymx3UDIwdGhCUGQ5M1Zkc2o3dlJMaGZzOVlhTjNOSVlyb0wvbk90elpabWRucUgwbzRQWmZBL0QKN3lHbjhsM0VGU2IzeWlRVW5jeUk4UUhjcEt3MDF6NzdPWWpFVnVuV1F5WUE1bE5oNlZ6VVFxMy9GNmpmblZ1cAp1NWpNOUMrc0RnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
 ---
 # Source: chainloop/templates/controlplane/jwt_cas_private_key.secret.yaml
 apiVersion: v1
@@ -370,7 +397,7 @@
   name: test-chainloop-controlplane-jwt-cas
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -408,7 +435,7 @@
   name: test-chainloop-cas
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -436,7 +463,7 @@
   name: test-chainloop-controlplane
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -1023,7 +1050,7 @@
   name: test-chainloop-cas-api
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -1051,7 +1078,7 @@
   name: test-chainloop-cas
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -1077,7 +1104,7 @@
   name: test-chainloop-controlplane-api
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -1105,7 +1132,7 @@
   name: test-chainloop-controlplane
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -1332,7 +1359,7 @@
   name: test-chainloop-cas
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -1348,9 +1375,9 @@
   template:
     metadata:
       annotations:
-        checksum/config: 2e369304caacfc3e57a4739c87d1c482f806bf2f905000f441ef47e58d8326a3
-        checksum/config-secret: cf09878bc234aa3a905491e58f4d69aa78cfbe11715c1963aa6bb8985a50c960
-        checksum/public-key-secret: c0444e34af2e02df26dc5950167a27ba96e63248396509094e8534fdd6fc5891
+        checksum/config: af1de31972b6e9dd2dda1f5e744794b89d6f8d067f73ab6d37c1dc1589c988bb
+        checksum/config-secret: e4524e938577d85d11e67225d35d390fed9991027b382cec6d527ad9f255ee7e
+        checksum/public-key-secret: 77ac8d4465985c1487c609df051e0296090f1bc2f0ac6bff65bf07378cc93393
       labels:
         app.kubernetes.io/name: chainloop
         app.kubernetes.io/instance: test
@@ -1414,7 +1441,7 @@
   name: test-chainloop-controlplane
   labels:
     app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.70.0
+    helm.sh/chart: chainloop-1.70.1
     app.kubernetes.io/instance: test
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/version: "v0.92.7"
@@ -1430,9 +1457,9 @@
   template:
     metadata:
       annotations:
-        checksum/config: b39ab1fd7ee1fbe3a2c60b8e9cad53f9c30961be5cd57f80f0767abbae65db46
-        checksum/secret-config: 964b0c214dd9396b3531c10dbcb7bbef897b606a03ea50713c76c91c152dd8b1
-        checksum/cas-private-key: 2f80993041c90d8a8f81b3b151f214be34009bcdb17a715426b24a707a0725c6
+        checksum/config: 75e9d2268a4c984adc62e982260205b85d4d2006b794d2b25581cb3c624a42cf
+        checksum/secret-config: cf481480ab3793f0203feb5872f600445e3baca419c01fa8e5a71a3bd6d85a58
+        checksum/cas-private-key: 02bfcc2663a4a0b35e63dd60d916ab115938d65d42fe88dc4d110e60ea703e1f
         kubectl.kubernetes.io/default-container: controlplane
       labels:
         app.kubernetes.io/name: chainloop
@@ -1499,6 +1526,8 @@
               mountPath: /tmp
             - name: jwt-cas-private-key
               mountPath: /secrets
+            - name: ejbca-ca-client
+              mountPath: /ca_secrets
       volumes:
         - name: config
           projected:
@@ -1513,6 +1542,9 @@
         - name: jwt-cas-private-key
           secret:
             secretName: test-chainloop-controlplane-jwt-cas
+        - name: ejbca-ca-client
+          secret:
+            secretName: test-chainloop-controlplane-keyless-ejbca-ca
 ---
 # Source: chainloop/charts/postgresql/templates/primary/statefulset.yaml
 apiVersion: apps/v1

```

### CODE REVIEW

**Review by migmartri — COMMENTED** [review]
Note that this is including the rest of the changes. you might need to move it to a clean PR.

Also, bump the chart version if you want to release it

**Comment by jiparis** [comment]
> Note that this is including the rest of the changes. you might need to move it to a clean PR.
> 
Yes, I will update the PR once https://github.com/chainloop-dev/chainloop/pull/1026 is merged.

> Also, bump the chart version if you want to release it
Ups, forgot it , thanks!

**Comment by jiparis** [comment]
PR updated and diffs as well.

**Review by migmartri — APPROVED** [review]
Awesome!

**Review by migmartri — APPROVED** [review]

**Pull request merged**
