### PR TITLE
feat: default inline CAS backend fallback

### PR DESCRIPTION
**Pull request by migmartri**
Create inline cas backend by default once the user signs up. 

```sh
$ ./chainloop cas-backend ls
┌──────────────────────────────────────┬──────────┬──────────┬─────────────────────────────────────┬───────────────┬─────────┐
│ ID                                   │ LOCATION │ PROVIDER │ DESCRIPTION                         │ LIMITS        │ DEFAULT │
├──────────────────────────────────────┼──────────┼──────────┼─────────────────────────────────────┼───────────────┼─────────┤
│ 888f6c17-34a5-4edb-86f2-63ab0c88a9d8 │          │ INLINE   │ Embed artifacts content in the atte │ MaxSize: 500K │ true    │
│                                      │          │          │ station (fallback)                  │               │         │
└──────────────────────────────────────┴──────────┴──────────┴─────────────────────────────────────┴───────────────┴─────────┘
```

This backend allows embedding files of up to 500KB, if you try to add a file bigger than the limit, the attestation process will fail

```sh
$ ./chainloop att add --name skynet-sbom --value ../../../internal/attestation/crafter/materials/testdata/sbom.spdx.json
ERR adding material: this file is too big for the INLINE CAS backend, please contact your administrator: fileSize=4.1M, maxSize=500K
```

a smaller file will do get embedded inline

```sh
$ ./chainloop att add --name skynet-sbom --value ~/Downloads/sbom.spdx.json 
INF material added to attestation
```

The attestation will now contain inline the content of the sbom. Note the `"chainloop.material.cas.inline` annotation and its array of bytes injected as `content`.

```json
{
   "_type": "https://in-toto.io/Statement/v0.1",
   "predicateType": "chainloop.dev/attestation/v0.2",
   "subject": [
      {
         "name": "chainloop.dev/workflow/waps2",
         "digest": {
            "sha256": "2435330ef47289f3e4ac81b6eba1d679fc86588f0a91c87f5d87e845f8e2ab7f"
         }
      }
   ],
   "predicate": {
      "buildType": "chainloop.dev/workflowrun/v0.1",
      "builder": {
         "id": "chainloop.dev/cli/v0.13.0-22-g0132187@sha256:0373e4a6dbf8a52f6e113c6293ef536d0f9748487891d6249fff1e1303fed326"
      },
      "materials": [
         {
            "annotations": {
               "chainloop.material.cas.inline": true,
               "chainloop.material.name": "skynet-sbom",
               "chainloop.material.type": "SBOM_SPDX_JSON"
            },
            "content": "ewogInNwZHhWZXJzaW9uIjogIlNQRFgtMi4zIiwKICJkYXRhTGljZW5zZSI6ICJDQzAtMS4wIiwKICJTUERYSUQiOiAiU1BEWFJlZi1ET0NVTUVOVCIsCiAibmFtZSI6ICJnaGNyLmlvL2NoYWlubG9vcC1kZXYvaW50ZWdyYXRpb24tZGVtbzp2MC4wLjQ2IiwKICJkb2N1bWVudE5hbWVzcGFjZSI6ICJodHRwczovL2FuY2hvcmUuY29tL3N5ZnQvaW1hZ2UvZ2hjci5pby9jaGFpbmxvb3AtZGV2L2ludGVncmF0aW9uLWRlbW8tdjAuMC40Ni0wNDUzMjMzZi03ZTc2LTQwYTYtOWE2NS0xNmQ5NDAyZDM1YTYiLAogImNyZWF0aW9uSW5mbyI6IHsKICAibGljZW5zZUxpc3RWZXJzaW9uIjogIjMuMjEiLAogICJjcmVhdG9ycyI6IFsKICAgIk9yZ2FuaXphdGlvbjogQW5jaG9yZSwgSW5jIiwKICAgIlRvb2w6IHN5ZnQtMC44NC4wIgogIF0sCiAgImNyZWF0ZWQiOiAiMjAyMy0wNy0wM1QxMTo0ODoyNVoiCiB9LAogInBhY2thZ2VzIjogWwogIHsKICAgIm5hbWUiOiAiZ2l0aHViLmNvbS9ibWl6ZXJhbnkvcGF0IiwKICAgIlNQRFhJRCI6ICJTUERYUmVmLVBhY2thZ2UtZ28tbW9kdWxlLWdpdGh1Yi5jb20tYm1pemVyYW55LXBhdC04ZWEzYjdjZjVlODQyMTY2IiwKICAgInZlcnNpb25JbmZvIjogInYwLjAuMC0yMDIxMDQwNjIxMzg0Mi1lNGI2NzYwYmRkNmYiLAogICAiZG93bmxvYWRMb2NhdGlvbiI6ICJOT0FTU0VSVElPTiIsCiAgICJmaWxlc0FuYWx5emVkIjogZmFsc2UsCiAgICJjaGVja3N1bXMiOiBbCiAgICB7CiAgICAgImFsZ29yaXRobSI6ICJTSEEyNTYiLAogICAgICJjaGVja3N1bVZhbHVlIjogIjgwZTNiZmI0ZDY0YzhlM2JkMzI5OTVhOTYzYjYyNzVjMmVmNjUwYjM0YjEyYjQ2ZGE3ZGUwYmEyZTllZDU0NGYiCiAgICB9CiAgIF0sCiAgICJzb3VyY2VJbmZvIjogImFjcXVpcmVkIHBhY2thZ2UgaW5mbyBmcm9tIGdvIG1vZHVsZSBpbmZvcm1hdGlvbjogL3NlcnZlciIsCiAgICJsaWNlbnNlQ29uY2x1ZGVkIjogIk5PQVNTRVJUSU9OIiwKICAgImxpY2Vuc2VEZWNsYXJlZCI6ICJOT0FTU0VSVElPTiIsCiAgICJjb3B5cmlnaHRUZXh0IjogIk5PQVNTRVJUSU9OIiwKICAgImV4dGVybmFsUmVmcyI6IFsKICAgIHsKICAgICAicmVmZXJlbmNlQ2F0ZWdvcnkiOiAiU0VDVVJJVFkiLAogICAgICJyZWZlcmVuY2VUeXBlIjogImNwZTIzVHlwZSIsCiAgICAgInJlZmVyZW5jZUxvY2F0b3IiOiAiY3BlOjIuMzphOmJtaXplcmFueTpwYXQ6djAuMC4wLTIwMjEwNDA2MjEzODQyLWU0YjY3NjBiZGQ2ZjoqOio6KjoqOio6KjoqIgogICAgfSwKICAgIHsKICAgICAicmVmZXJlbmNlQ2F0ZWdvcnkiOiAiUEFDS0FHRS1NQU5BR0VSIiwKICAgICAicmVmZXJlbmNlVHlwZSI6ICJwdXJsIiwKICAgICAicmVmZXJlbmNlTG9jYXRvciI6ICJwa2c6Z29sYW5nL2dpdGh1Yi5jb20vYm1pemVyYW55L3BhdEB2MC4wLjAtMjAyMTA0MDYyMTM4NDItZTRiNjc2MGJkZDZmIgogICAgfQogICBdCiAgfSwKICB7CiAgICJuYW1lIjogImdpdGh1Yi5jb20vY2hhaW5sb29wLWRldi9pbnRlZ3JhdGlvbi1kZW1vIiwKICAgIlNQRFhJRCI6ICJTUERYUmVmLVBhY2thZ2UtZ28tbW9kdWxlLWdpdGh1Yi5jb20tY2hhaW5sb29wLWRldi1pbnRlZ3JhdGlvbi1kZW1vLWFkZjk3YTAyYTlmMWI1YzkiLAogICAidmVyc2lvbkluZm8iOiAidjAuMC40NiIsCiAgICJkb3dubG9hZExvY2F0aW9uIjogIk5PQVNTRVJUSU9OIiwKICAgImZpbGVzQW5hbHl6ZWQiOiBmYWxzZSwKICAgInNvdXJjZUluZm8iOiAiYWNxdWlyZWQgcGFja2FnZSBpbmZvIGZyb20gZ28gbW9kdWxlIGluZm9ybWF0aW9uOiAvc2VydmVyIiwKICAgImxpY2Vuc2VDb25jbHVkZWQiOiAiTk9BU1NFUlRJT04iLAogICAibGljZW5zZURlY2xhcmVkIjogIk5PQVNTRVJUSU9OIiwKICAgImNvcHlyaWdodFRleHQiOiAiTk9BU1NFUlRJT04iLAogICAiZXh0ZXJuYWxSZWZzIjogWwogICAgewogICAgICJyZWZlcmVuY2VDYXRlZ29yeSI6ICJTRUNVUklUWSIsCiAgICAgInJlZmVyZW5jZVR5cGUiOiAiY3BlMjNUeXBlIiwKICAgICAicmVmZXJlbmNlTG9jYXRvciI6ICJjcGU6Mi4zOmE6Y2hhaW5sb29wLWRldjppbnRlZ3JhdGlvbi1kZW1vOnYwLjAuNDY6KjoqOio6KjoqOio6KiIKICAgIH0sCiAgICB7CiAgICAgInJlZmVyZW5jZUNhdGVnb3J5IjogIlNFQ1VSSVRZIiwKICAgICAicmVmZXJlbmNlVHlwZSI6ICJjcGUyM1R5cGUiLAogICAgICJyZWZlcmVuY2VMb2NhdG9yIjogImNwZToyLjM6YTpjaGFpbmxvb3AtZGV2OmludGVncmF0aW9uX2RlbW86djAuMC40NjoqOio6KjoqOio6KjoqIgogICAgfSwKICAgIHsKICAgICAicmVmZXJlbmNlQ2F0ZWdvcnkiOiAiU0VDVVJJVFkiLAogICAgICJyZWZlcmVuY2VUeXBlIjogImNwZTIzVHlwZSIsCiAgICAgInJlZmVyZW5jZUxvY2F0b3IiOiAiY3BlOjIuMzphOmNoYWlubG9vcF9kZXY6aW50ZWdyYXRpb24tZGVtbzp2MC4wLjQ2Oio6KjoqOio6KjoqOioiCiAgICB9LAogICAgewogICAgICJyZWZlcmVuY2VDYXRlZ29yeSI6ICJTRUNVUklUWSIsCiAgICAgInJlZmVyZW5jZVR5cGUiOiAiY3BlMjNUeXBlIiwKICAgICAicmVmZXJlbmNlTG9jYXRvciI6ICJjcGU6Mi4zOmE6Y2hhaW5sb29wX2RldjppbnRlZ3JhdGlvbl9kZW1vOnYwLjAuNDY6KjoqOio6KjoqOio6KiIKICAgIH0sCiAgICB7CiAgICAgInJlZmVyZW5jZUNhdGVnb3J5IjogIlNFQ1VSSVRZIiwKICAgICAicmVmZXJlbmNlVHlwZSI6ICJjcGUyM1R5cGUiLAogICAgICJyZWZlcmVuY2VMb2NhdG9yIjogImNwZToyLjM6YTpjaGFpbmxvb3A6aW50ZWdyYXRpb24tZGVtbzp2MC4wLjQ2Oio6KjoqOio6KjoqOioiCiAgICB9LAogICAgewogICAgICJyZWZlcmVuY2VDYXRlZ29yeSI6ICJTRUNVUklUWSIsCiAgICAgInJlZmVyZW5jZVR5cGUiOiAiY3BlMjNUeXBlIiwKICAgICAicmVmZXJlbmNlTG9jYXRvciI6ICJjcGU6Mi4zOmE6Y2hhaW5sb29wOmludGVncmF0aW9uX2RlbW86djAuMC40NjoqOio6KjoqOio6KjoqIgogICAgfSwKICAgIHsKICAgICAicmVmZXJlbmNlQ2F0ZWdvcnkiOiAiUEFDS0FHRS1NQU5BR0VSIiwKICAgICAicmVmZXJlbmNlVHlwZSI6ICJwdXJsIiwKICAgICAicmVmZXJlbmNlTG9jYXRvciI6ICJwa2c6Z29sYW5nL2dpdGh1Yi5jb20vY2hhaW5sb29wLWRldi9pbnRlZ3JhdGlvbi1kZW1vQHYwLjAuNDYiCiAgICB9CiAgIF0KICB9LAogIHsKICAgIm5hbWUiOiAiZ2l0aHViLmNvbS9tYXR0bi9nby1zcWxpdGUzIiwKICAgIlNQRFhJRCI6ICJTUERYUmVmLVBhY2thZ2UtZ28tbW9kdWxlLWdpdGh1Yi5jb20tbWF0dG4tZ28tc3FsaXRlMy0zMjU5ZDQwYTIyNjM2YTJiIiwKICAgInZlcnNpb25JbmZvIjogInYxLjE0LjE2IiwKICAgImRvd25sb2FkTG9jYXRpb24iOiAiTk9BU1NFUlRJT04iLAogICAiZmlsZXNBbmFseXplZCI6IGZhbHNlLAogICAiY2hlY2tzdW1zIjogWwogICAgewogICAgICJhbGdvcml0aG0iOiAiU0hBMjU2IiwKICAgICAiY2hlY2tzdW1WYWx1ZSI6ICJjOGU0MTEwMzQ0Njk0YjkzYzVjZmZhMjI5MDZjMDExMmFiYzA1YTE1YTBlNmU3ZDFjZjgxMTMyZTNjMjk1MzU2IgogICAgfQogICBdLAogICAic291cmNlSW5mbyI6ICJhY3F1aXJlZCBwYWNrYWdlIGluZm8gZnJvbSBnbyBtb2R1bGUgaW5mb3JtYXRpb246IC9zZXJ2ZXIiLAogICAibGljZW5zZUNvbmNsdWRlZCI6ICJOT0FTU0VSVElPTiIsCiAgICJsaWNlbnNlRGVjbGFyZWQiOiAiTk9BU1NFUlRJT04iLAogICAiY29weXJpZ2h0VGV4dCI6ICJOT0FTU0VSVElPTiIsCiAgICJleHRlcm5hbFJlZnMiOiBbCiAgICB7CiAgICAgInJlZmVyZW5jZUNhdGVnb3J5IjogIlNFQ1VSSVRZIiwKICAgICAicmVmZXJlbmNlVHlwZSI6ICJjcGUyM1R5cGUiLAogICAgICJyZWZlcmVuY2VMb2NhdG9yIjogImNwZToyLjM6YTptYXR0bjpnby1zcWxpdGUzOnYxLjE0LjE2Oio6KjoqOio6KjoqOioiCiAgICB9LAogICAgewogICAgICJyZWZlcmVuY2VDYXRlZ29yeSI6ICJTRUNVUklUWSIsCiAgICAgInJlZmVyZW5jZVR5cGUiOiAiY3BlMjNUeXBlIiwKICAgICAicmVmZXJlbmNlTG9jYXRvciI6ICJjcGU6Mi4zOmE6bWF0dG46Z29fc3FsaXRlMzp2MS4xNC4xNjoqOio6KjoqOio6KjoqIgogICAgfSwKICAgIHsKICAgICAicmVmZXJlbmNlQ2F0ZWdvcnkiOiAiUEFDS0FHRS1NQU5BR0VSIiwKICAgICAicmVmZXJlbmNlVHlwZSI6ICJwdXJsIiwKICAgICAicmVmZXJlbmNlTG9jYXRvciI6ICJwa2c6Z29sYW5nL2dpdGh1Yi5jb20vbWF0dG4vZ28tc3FsaXRlM0B2MS4xNC4xNiIKICAgIH0KICAgXQogIH0KIF0sCiAiZmlsZXMiOiBbCiAgewogICAiZmlsZU5hbWUiOiAiL3NlcnZlciIsCiAgICJTUERYSUQiOiAiU1BEWFJlZi1GaWxlLXNlcnZlci1iODAwMjk5NDQyMWE2OGNlIiwKICAgImNoZWNrc3VtcyI6IFsKICAgIHsKICAgICAiYWxnb3JpdGhtIjogIlNIQTEiLAogICAgICJjaGVja3N1bVZhbHVlIjogIjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiCiAgICB9CiAgIF0sCiAgICJsaWNlbnNlQ29uY2x1ZGVkIjogIk5PQVNTRVJUSU9OIiwKICAgImNvcHlyaWdodFRleHQiOiAiIiwKICAgImNvbW1lbnQiOiAibGF5ZXJJRDogc2hhMjU2OmYxNmMzZWFlNjExMWU0YTkyNWVlOGFjZjY0OTUxYmI3ZTA5YTc1NjRkMDU5NDM4ZjU0NzQ5ZTY5NGIxMmM5MWUiCiAgfQogXSwKICJyZWxhdGlvbnNoaXBzIjogWwogIHsKICAgInNwZHhFbGVtZW50SWQiOiAiU1BEWFJlZi1QYWNrYWdlLWdvLW1vZHVsZS1naXRodWIuY29tLW1hdHRuLWdvLXNxbGl0ZTMtMzI1OWQ0MGEyMjYzNmEyYiIsCiAgICJyZWxhdGVkU3BkeEVsZW1lbnQiOiAiU1BEWFJlZi1GaWxlLXNlcnZlci1iODAwMjk5NDQyMWE2OGNlIiwKICAgInJlbGF0aW9uc2hpcFR5cGUiOiAiT1RIRVIiLAogICAiY29tbWVudCI6ICJldmlkZW50LWJ5OiBpbmRpY2F0ZXMgdGhlIHBhY2thZ2UncyBleGlzdGVuY2UgaXMgZXZpZGVudCBieSB0aGUgZ2l2ZW4gZmlsZSIKICB9LAogIHsKICAgInNwZHhFbGVtZW50SWQiOiAiU1BEWFJlZi1QYWNrYWdlLWdvLW1vZHVsZS1naXRodWIuY29tLWJtaXplcmFueS1wYXQtOGVhM2I3Y2Y1ZTg0MjE2NiIsCiAgICJyZWxhdGVkU3BkeEVsZW1lbnQiOiAiU1BEWFJlZi1GaWxlLXNlcnZlci1iODAwMjk5NDQyMWE2OGNlIiwKICAgInJlbGF0aW9uc2hpcFR5cGUiOiAiT1RIRVIiLAogICAiY29tbWVudCI6ICJldmlkZW50LWJ5OiBpbmRpY2F0ZXMgdGhlIHBhY2thZ2UncyBleGlzdGVuY2UgaXMgZXZpZGVudCBieSB0aGUgZ2l2ZW4gZmlsZSIKICB9LAogIHsKICAgInNwZHhFbGVtZW50SWQiOiAiU1BEWFJlZi1QYWNrYWdlLWdvLW1vZHVsZS1naXRodWIuY29tLWNoYWlubG9vcC1kZXYtaW50ZWdyYXRpb24tZGVtby1hZGY5N2EwMmE5ZjFiNWM5IiwKICAgInJlbGF0ZWRTcGR4RWxlbWVudCI6ICJTUERYUmVmLUZpbGUtc2VydmVyLWI4MDAyOTk0NDIxYTY4Y2UiLAogICAicmVsYXRpb25zaGlwVHlwZSI6ICJPVEhFUiIsCiAgICJjb21tZW50IjogImV2aWRlbnQtYnk6IGluZGljYXRlcyB0aGUgcGFja2FnZSdzIGV4aXN0ZW5jZSBpcyBldmlkZW50IGJ5IHRoZSBnaXZlbiBmaWxlIgogIH0sCiAgewogICAic3BkeEVsZW1lbnRJZCI6ICJTUERYUmVmLURPQ1VNRU5UIiwKICAgInJlbGF0ZWRTcGR4RWxlbWVudCI6ICJTUERYUmVmLURPQ1VNRU5UIiwKICAgInJlbGF0aW9uc2hpcFR5cGUiOiAiREVTQ1JJQkVTIgogIH0KIF0KfQo=",
            "digest": {
               "sha256": "984960100e9fd63df132760d9d8b8166c52e875ad5f60e3a191eff4f28bc3094"
            },
            "name": "sbom.spdx.json"
         }
      ],
      "metadata": {
         "finishedAt": "2023-07-18T12:58:54.173929879+02:00",
         "initializedAt": "2023-07-18T10:51:26.567380238Z",
         "name": "waps2",
         "project": "bar",
         "team": "",
         "workflowID": "c80c8789-d7a5-42a4-869f-baace169e52e",
         "workflowRunID": "25dfc828-c8af-4cb5-9ec4-4dcb5379dfb1"
      },
      "runnerType": "RUNNER_TYPE_UNSPECIFIED"
   }
}
```

The operator can easily change the CAS backend to an OCI backend one

```sh
$ ./chainloop cas-backend add oci --repo us-central1-docker.pkg.dev/axiomatic-grove-366622/chainloop-demo-org --username _json_key --password "$(cat ...service-account-devel.json)" --default                         
You are changing the default CAS backend in your organization
Please confirm to continue y/N
y

$ ./chainloop cas-backend ls         
┌──────────────────────────────────────┬─────────────────────────────────────┬──────────┬─────────────────────────────────────┬───────────────┬─────────┐
│ ID                                   │ LOCATION                            │ PROVIDER │ DESCRIPTION                         │ LIMITS        │ DEFAULT │
├──────────────────────────────────────┼─────────────────────────────────────┼──────────┼─────────────────────────────────────┼───────────────┼─────────┤
│ 2770c049-d8c4-4a61-922c-2020e3ddc360 │ us-central1-docker.pkg.dev/axiomati │ OCI      │                                     │ MaxSize: 100M │ true    │
│                                      │ c-grove-366622/chainloop-demo-org   │          │                                     │               │         │
├──────────────────────────────────────┼─────────────────────────────────────┼──────────┼─────────────────────────────────────┼───────────────┼─────────┤
│ 888f6c17-34a5-4edb-86f2-63ab0c88a9d8 │                                     │ INLINE   │ Embed artifacts content in the atte │ MaxSize: 500K │ false   │
│                                      │                                     │          │ station (fallback)                  │               │         │
└──────────────────────────────────────┴─────────────────────────────────────┴──────────┴─────────────────────────────────────┴───────────────┴─────────┘
```

and note how now the max size of the artifacts is 100MB instead, so now we should be able to actually upload the bigger file that failed before

```
$ ./chainloop att add --name skynet-sbom --value ../../../internal/attestation/crafter/materials/testdata/sbom.spdx.json
INF uploading sbom.spdx.json - sha256:fe2636fb6c698a29a315278b762b2000efd5959afe776ee4f79f1ed523365a33
INF material added to attestation
```
and the attestation now only includes the reference (as expected). Note the `chainloop.material.cas` annotation.

```json
{
   "_type": "https://in-toto.io/Statement/v0.1",
   "predicateType": "chainloop.dev/attestation/v0.2",
   "subject": [
      {
         "name": "chainloop.dev/workflow/waps2",
         "digest": {
            "sha256": "3653945bc716fe53935fce775a39fe3aefa1d8b26480da2da68aff3a87f83075"
         }
      }
   ],
   "predicate": {
      "buildType": "chainloop.dev/workflowrun/v0.1",
      "builder": {
         "id": "chainloop.dev/cli/v0.13.0-22-g0132187@sha256:0373e4a6dbf8a52f6e113c6293ef536d0f9748487891d6249fff1e1303fed326"
      },
      "materials": [
         {
            "annotations": {
               "chainloop.material.cas": true,
               "chainloop.material.name": "skynet-sbom",
               "chainloop.material.type": "SBOM_SPDX_JSON"
            },
            "digest": {
               "sha256": "fe2636fb6c698a29a315278b762b2000efd5959afe776ee4f79f1ed523365a33"
            },
            "name": "sbom.spdx.json"
         }
      ],
      "metadata": {
         "finishedAt": "2023-07-18T13:03:27.467361354+02:00",
         "initializedAt": "2023-07-18T11:03:00.235043011Z",
         "name": "waps2",
         "project": "bar",
         "team": "",
         "workflowID": "c80c8789-d7a5-42a4-869f-baace169e52e",
         "workflowRunID": "99636d25-6ca2-41eb-9b2d-aa107e1dfc05"
      },
      "runnerType": "RUNNER_TYPE_UNSPECIFIED"
   }

```

This inline CAS backend has some special properties

- it has a smaller upload size limit, 500KB vs 100MB of regular backend
- Does not require validation

We've added a fallback field that indicates that a backend is the default fallback and can not be deleted.

Refs #201 #223

### CODE REVIEW

**Comment by danlishka** [comment]
The only comment I have is related to integrations. I think we need a way to render attestations in a way you can send it to Slack, Discord etc. - we can just remove inline materials.

**Review by danlishka — APPROVED** [review]
LGTM. The onboarding will get much easier now. We just need to make sure you still can send notifications and UX is not completely destroyed there

**Comment by migmartri** [comment]
> The only comment I have is related to integrations. I think we need a way to render attestations in a way you can send it to Slack, Discord etc. - we can just remove inline materials.

We should probably not to send the actual attestation json to these messaging formats but instead a rendered/summarized version of it. Sending an attestation removing some content will technically invalidate/corrupt the attestation so I am not sure it's the best path forward. That said, I just added a follow up task to tackle some of this https://github.com/chainloop-dev/chainloop/issues/248

**Comment by migmartri** [comment]
> LGTM. The onboarding will get much easier now. We just need to make sure you still can send notifications and UX is not completely destroyed there

could you elaborate what you mean by completely destroyed? It would be good to add those thoughts here https://github.com/chainloop-dev/chainloop/issues/248

Thanks!

**Pull request merged**
