### PR TITLE
feat(documentation): Add documentation about Prometheus

### LINKED ISSUE #1115: Document Prometheus integration
With the addition of the Prometheus Integration, let's update the documentation so we can show how to enable the feature using the Chart values.

### PR DESCRIPTION
**Pull request by javirln**
This patch documents the Prometheus integration that includes:
- How to add the new configuration to Chainloop's Chart
- Generated the needed requirements
- Examples in how to configure Prometheus and Prometheus Operator
- Example of integration in Grafana
- Example of integration in Alertmanager

Closes #1115

### CODE REVIEW

**Comment by javirln** [comment]
@migmartri documentation updated.

**Review by migmartri — APPROVED** [review]
Cool, have you verified that the docusaurus site builds?

**Comment by migmartri** [comment]
> Refs https://github.com/chainloop-dev/chainloop/issues/1115

replace refs for `closes` :)

**Comment by javirln** [comment]
> Cool, have you verified that the docusaurus site builds?
> 
> Sometimes broken links can't be detected until the build is performed, this is smth we should check in the CI eventually too.

Yes, I have ran it locally and everything builds without problem. Didn't paste a screenshot because it's too large for it to be shown.

**Pull request merged**
